### ISSUE TITLE
Integrate static code analysis using SonarCloud with GluuFederation

### ISSUE THREAD

**Issue by ossdhaval** [GluuFederation/oxAuth#1574]
Integrate SonarCloud with following repositories in Gluu.

- [x] scim GluuFederation/scim#29
- [x] oxauth GluuFederation/oxAuth#1575
- [x] oxtrust GluuFederation/oxTrust#2097
- [x] shib GluuFederation/oxShibboleth#101
- [ ] opendj
- [x] fido2 GluuFederation/fido2#13
- [x] gluu-passport (doesn't need code change since it is JS code)
- [x] casa GluuFederation/casa#151
- [x] oxd-server GluuFederation/oxd#575
- [x] gluu-admin-ui (doesn't need code change since it is JS code)
- [x] Link sonarcloud with each of above repo
- [x] create workflow script in cloud-native-edition GluuFederation/cloud-native-edition#372 GluuFederation/cloud-native-edition#379
- [ ] verify that code analysis is happening correctly for each repoes jans-auth is running with open
